### ISSUE TITLE
Traceback due to possible bad data from bf4db.com

### ISSUE THREAD

**Issue by robled** [DontCamp/bf4-server-status#19]
````
Traceback (most recent call last):
  File "/var/www/dontcamp.com/bf4-server-status/bf4-server-status.py", line 306, in <module>
    _main()
  File "/var/www/dontcamp.com/bf4-server-status/bf4-server-status.py", line 297, in _main
    key=lambda k: '%d%s' % (player_data[k]['cheatscore'], k.name.lower()))
  File "/var/www/dontcamp.com/bf4-server-status/bf4-server-status.py", line 297, in <lambda>
    key=lambda k: '%d%s' % (player_data[k]['cheatscore'], k.name.lower()))
TypeError: %d format: a number is required, not NoneType
````

There are times when bf4db.com cannot give us a cheat score and/or other data, and in those cases we should handle it.

**Comment by robled** [comment]
All cheatscores that are None are now -1.
